### ISSUE TITLE
gmaster clone

### ISSUE THREAD

**Issue by JonasGroeger** [francoiscabrol/gitmaster#1]
Hello!

I would like to see a `gmaster clone` command that takes data from a GitHub or GitLab API and creates an appropriate `.gmaster` file, as well as clones the repositories.

**Comment by francoiscabrol** [comment]
Hey 
you have already `gmaster dump` that create a .gitmaster file with all the already cloned repositories in the current folder. So what you want is a `gmaster clone ssh://gitrepo` command that clone the repo and update (or create) the .gitmaster file, right? I think that's a good idea, I could implement it :)
