### ISSUE TITLE
Install as unprivileged user

### ISSUE THREAD

**Issue by bodograumann** [francoiscabrol/gitmaster#3]
If you run `install.sh` it will try to call `sudo`. This is not required if the target directory is owned by the user itself. (In fact I don’t even have the sudo command available.)
May be you could provide a parameter for `install.sh` which disables use of `sudo`.

**Comment by francoiscabrol** [comment]
Humm yes I think I could even remove the sudo and recommend to install it in a folder own by the user...

**Comment by francoiscabrol** [comment]
I changed the script to install by default in the $HOME/bin folder and have removed the sudo command from the script.
Now you have to run 
```
curl https://raw.githubusercontent.com/francoiscabrol/gitmaster/master/install.sh | GITMASTER_PATH=$HOME/bin bash -x
```
Does it solve your issue? I tried locally for me the script is working...

**Comment by bodograumann** [comment]
Yes thanks that is great.
