### ISSUE TITLE
Find repositories recursively

### ISSUE THREAD

**Issue by bodograumann** [francoiscabrol/gitmaster#4]
Currently `gitmaster` only looks for git repositories exactly one level below the target path.

I personally have a structure of `[…]/projects/<project-name>/<repo-name>/.git`, where each project can contain multiple repositories. Unfortunately this makes `gitmaster` unusable for me.

This feature might also be useful, for users of `git-submodule`.

Note: When finding repositories recursively you need to be careful about symlinks. I would suggest to follow them, but deduplicate any found paths.

**Comment by francoiscabrol** [comment]
I guess the possibility to specify the level of recursion would be the best.
It would be something like `gmaster --level 2` or `gmaster -L 2`. By default the level would stay set to 1. Like that it would preserve the speed.

**Comment by bodograumann** [comment]
Yes, that seems sensible.

**Comment by bodograumann** [comment]
I feel like something broke, when you added those changes @francoiscabrol . It now says ”no remote” as status for a lot of repositories. That’s not supposed to happen when they do have valid remotes, is it?

**Comment by francoiscabrol** [comment]
weird for me it's working...

**Comment by bodograumann** [comment]
Could it be, that I need to run `gmaster dump --level 2` beforehand?

**Comment by francoiscabrol** [comment]
yes just add `--level 2` to any command
