### ISSUE TITLE
gmaster dump can not handle remote url

### ISSUE THREAD

**Issue by bodograumann** [francoiscabrol/gitmaster#6]
I‘m not quite sure, what exactly the problem is, but when I run `gmaster dump --level 2` with a repository pointing to a remote of the form

    ssh://git@my.git.server:1022/some/repo/dir

it gives the error:

> [ERROR] app-hq: com.francoiscabrol.gitmaster.git.GitCmdError: Impossible to parse the remote url of app-hq

It could be because of the non-standard ssh-port. The remotes `git@github.com:bodograumann/mu-repo.git` and `https://github.com/OpenAPITools/openapi-generator.git` do work.

**Comment by francoiscabrol** [comment]
ok thank you for reporting the issue. I will try to reproduce

**Comment by bodograumann** [comment]
It really seems to be a general problem. I’m sorry that I can’t help in debugging as I don’t know scala.

This is how to easily reproduce the problem:

```
curl https://raw.githubusercontent.com/francoiscabrol/gitmaster/master/install.sh | GITMASTER_PATH=./ bash -x
git clone https://github.com/francoiscabrol/gitmaster.git
./gmaster
```

**Output:**
```
 | gitmaster No remote
```

**Comment by francoiscabrol** [comment]
Thank you for your help! it should not be hard to fix. i will try this weekend

**Comment by bodograumann** [comment]
This feels a little awkward, but the problem is still there with the above example…
Could you please have another look, if you find the time?

Happy holidays :-)

**Comment by francoiscabrol** [comment]
I think there were two problems.
- The first one was when you tried to run `gmaster` in a folder with a repository pointing to an url like `ssh://git@github.com`.
I reproduced this problem with the following commands:
```
git clone ssh://git@github.com/francoiscabrol/ranger.vim
gmaster
```
This first problem is now fixed for me with the previous pull request.

- The second problem is the general problem you talked about and you reproduced with
```
curl https://raw.githubusercontent.com/francoiscabrol/gitmaster/master/install.sh | GITMASTER_PATH=./ bash -x
git clone https://github.com/francoiscabrol/gitmaster.git
./gmaster
```
This second issue was not reproductible for me and this last command always worked for me:
```
❯ ./gmaster
 | gitmaster Up to date
```

**Comment by francoiscabrol** [comment]
what do you get if go into your gitmaster folder and you run `git remote get-url origin`?
you should get the remote url `https://github.com/francoiscabrol/gitmaster.git`

**Comment by bodograumann** [comment]
Yes I do:
```
$ git remote get-url origin                                                                                                                                     
https://github.com/francoiscabrol/gitmaster.git
```

Maybe it depends on the software version…
```
$ java-config -L                                                                                                                                                
The following VMs are available for generation-2:                                                                                                                                            
*)      IcedTea JDK 3.9.0 [icedtea-bin-8]

 $ git --version                                                                                                                                                 
git version 2.18.1
```

I also created a new unix user to make sure that no git settings are interfering. The result was the same.

**Comment by francoiscabrol** [comment]
ok... I guess the versions are good and if you get the good output for `git remote get-url origin` I don't see why it does not work :/ Are you sure you are using the last gmaster version?

there is also something that I don't understand: in your first comment 

> It could be because of the non-standard ssh-port. The remotes `git@github.com:bodograumann/mu-repo.git` and `https://github.com/OpenAPITools/openapi-generator.git` do work.

you said that it was working with https://* remote urls... so what changed after?

**Comment by francoiscabrol** [comment]
oh I reproduced the issue with an other computer!

**Comment by francoiscabrol** [comment]
git changed its output recently 'Your branch is up-to-date' is now 'You branch is up to date' :/

**Comment by bodograumann** [comment]
Wow, good catch! I was really tearing at my hair about this one. Now it works :-)
